### ISSUE TITLE
Version displayed during startup

### ISSUE THREAD

**Issue by ccapell** [bitops-plugins/terraform#2]
During startup Terraform version is displayed, but that is not the version being used.
```
~#~#~#~BITOPS ENVIRONMENT VARIABLES~#~#~#~
.....
        BITOPS_TERRAFORM_VERSION=0.13.2
2022-07-22 19:46:49,665 root         INFO 
```

Same issue is in the schema

The versions displayed should be the versions that are being used.

**Comment by shyamrayaprolu** [comment]
This config is not being used in the current release. So this config has been removed from the schema

**Comment by mickmcgrath13** [comment]
@shyamrayaprolu link to PR or commit?

**Comment by armab** [comment]
Closing as the version config is not present in the schema.
