### ISSUE TITLE
Stack-Action

### ISSUE THREAD

**Issue by ccapell** [bitops-plugins/terraform#5]
Set stackaction to default to plan, should not be required config value.  Use Command line to set to apply.
Still allow users to set to apply via config

**Comment by shyamrayaprolu** [comment]
Also need a discussion on setting stack-action as a cli vs options config...

**Comment by mickmcgrath13** [comment]
@shyamrayaprolu does it default to `plan` ?

@PhillypHenning can you chime in on why stack-action was in `cli` rather than `options` initially?

**Comment by armab** [comment]
Closing as stack-action defaults to `plan` these days.

It's interesting fact based on discussion here, that in the past `stack-action` was part of `cli`, then was moved to `options` and now we plan to move it again to `cli` per #17 cc @PhillypHenning.
